### ISSUE TITLE
Add missing javassist dependency

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-stack#15]
Thymeleaf template engine requires Javassist.

We need to add this dependency again:

```
<dependency>
	<groupId>org.javassist</groupId>
	<artifactId>javassist</artifactId>
	<version>3.18.2-GA</version>
</dependency>
```

This dependency needs to be added into the web stack. We need an automated example to check the fix.

**Comment by purplefox** [comment]
We need to be very careful about that as Netty can behave differently if Javassist is on the classpath and requires a specific version.

**Comment by cescoffier** [comment]
Yes,

Previously we depended on 3.18.1-GA. We removed it when we dropped the mysql/posgres client. The safest would be to reuse the same version.
