### ISSUE TITLE
Update scripts to enable vertx-sync

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-stack#19]
We should update the vertx scripts so they (optionally) allow vertx-sync to be easily enabled.

This means adding the javaagent as described here https://github.com/vert-x3/vertx-sync/blob/master/README.adoc

Also the debugging options.

**Comment by cescoffier** [comment]
The user can configure `$JAVA_OPTS` or `$VERTX_OPTS` for this.

**Comment by purplefox** [comment]
True, but maybe we should make it simpler for them? Adding the javaagent path can be tricky and prone to error as it will have to reference the jar with the correct version in the lib directory.

We could change the script so it checked for a simple environment variable(e.g. ENABLE_SYNC) and if set then the script could add the -javaagent arg with the correct path.
