### ISSUE TITLE
vertx stack cache aether infos

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-stack#25]
- snapshot : cached for one day
- info should be cached in $VERTX_HOME/something_that_makes_sense

**Comment by cescoffier** [comment]
I'm not sure we should cache snapshots. It's probably better to let Aether deal with snapshot caching.

**Comment by vietj** [comment]
if we don't do it for snapshot, we cannot really test this feature with SNAPSHOT when trying the stack ourselves, right ?

**Comment by cescoffier** [comment]
I've test using vertx-core 3.1 explicitly to test released artifacts. So test would use this too.
In addition I can build a stack using whatever release artifact from Maven central.

**Comment by vietj** [comment]
I'm trying the tool and usability and how people are going to use it, howe it goes etc..., we need to have a --cache-snapshot configuration or something like that ?

**Comment by vietj** [comment]
or as an env variable
