### ISSUE TITLE
stack-docs relies on -docs artifacts which are not packaged by default

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-stack#27]
With the last vertx-ext-parent, the -docs artifacts are not packaged by default, but the stack-docs project still relies on them (so right now it uses outdated versions).

**Comment by cescoffier** [comment]
To get stack-docs built, I've enabled the -docs profile in the TCP event bus bridge.

**Comment by vietj** [comment]
please see https://github.com/vert-x3/vertx-ext-parent/commit/0b6d0d99dc1d021e926040f8197a28bc2028b162

**Comment by vietj** [comment]
use vertx-ext-parent-20

**Comment by cescoffier** [comment]
20 does not exist. Did you mean 19 ?

**Comment by vietj** [comment]
pick the latest, I'm sure it does the packaging :-)

**Comment by vietj** [comment]
https://github.com/vert-x3/vertx-ext-parent/blob/master/parent/pom.xml#L155

**Comment by cescoffier** [comment]
All projects updated.
