### ISSUE TITLE
Use the Vert.x log wrapper instead of java.util.logging.Logger

### ISSUE THREAD

**Issue by mguillet** [vert-x3/vertx-stack#34]
Any reason we are using `java.util.logging.Logger` instead of `io.vertx.core.logging.Logger` ? 

I could spot several uses of `java.util.logging.Logger` for instance in `io.vertx.maven.resolver.ResolverImpl`.

This break our nice logs since we're using `SLF4J` instead of `JUL`.

I can easily make the change and a PR if this change to Vert.x logger is accepted.

Thanks!

**Comment by cescoffier** [comment]
In the Resolve command ? We could change that without any issue.

**Comment by mguillet** [comment]
Here are all the classes using JUL classes instead of Vert.x ones:
```
stack-manager/src/main/java/io/vertx/stack/model/StackResolution.java
stack-manager/src/main/java/io/vertx/stack/resolver/ResolverImpl.java
stack-manager/src/main/java/io/vertx/stack/utils/Cache.java
stack-manager/src/test/java/io/vertx/stack/utils/LocalRepoBuilder.java
```
Is that OK for all of them to change?

**Comment by cescoffier** [comment]
Yes.
