### ISSUE TITLE
missing wiki links

### ISSUE THREAD

**Issue by eutheria** [vert-x3/vertx-stack#42]
I noticed that the wiki pages linked from: http://vertx.io/docs/vertx-auth-jwt/java/ 

http://vertx.io/docs/apidocs/javax/crypto/Mac.html http://vertx.io/docs/apidocs/java/security/Signature.html 

are missing, it was suggested that these could be links to the jdk javadocs.

**Comment by cescoffier** [comment]
We should compute the javadoc with links to:

* Java javadoc
* Hazelcast
* Netty
* Jackson

**Comment by cescoffier** [comment]
Fixed in the vertx-auth project.
