### ISSUE TITLE
Java version older

### ISSUE THREAD

**Issue by coding2012** [vert-x3/vertx-stack#43]
Even though the latest version of Vertx docker image is only about 14 days old, the Java version is quite old. I recommend doing an explicit docker pull java:8 prior to building the Vertx image.

**Comment by cescoffier** [comment]
Even if we should update to a newer version, using `java:8` introduce variability that can be very hard to understand. The image would depend on "what" java:8 is at the build time. It could be different a few hours later.

**Comment by coding2012** [comment]
Excellent, thank you Clement!
