### ISSUE TITLE
Typescript definitions for vertx3-eventbus-client

### ISSUE THREAD

**Issue by oddeirik** [vert-x3/vertx-stack#61]
I'm currently using [vertx3-eventbus-client](https://www.npmjs.com/package/vertx3-eventbus-client) in a web client application to communicate with a Java application via the EventBus.

The web client is written in Typescript, but there's no definition file for the eventbus client. Currently I've worked around this by simply adding vertx-eventbus.js and sockjs.js as <script> sources in the index file and then doing `declare var EventBus: any;` in Typescript source files that need it. That makes the Typescript compiler happy, but not the developer since you don't get any of the actual useful stuff like type checking, auto-completion, etc. 😄

I'm not sure whether this issue is something that would relate to npm-client or vertx-web, since the latter is what actually generates vertx-eventbus.js (?).

**Comment by pmlopes** [comment]
@oddeirik Could you provide a pull request for it?

**Comment by oddeirik** [comment]
I'm completely new to Typescript myself, but I could certainly give it a try!

**Comment by tombensve** [comment]
I did the following, but it took me a while to figure it out:

`import EventBus from 'vertx3-eventbus-client';`
`let eventBus = EventBus("http://locahost:8080/eventbus", {});`

I first tries doing `new EventBus(...)`, but that failed! This seems to work. It is trying to access the specified URL at least. I haven't made the server code yet so I haven't fully verified it yet. 

Doing a browserify however make this code fail! I assume it is because vertx3-eventbus-client is not a correct node module, and browserify works with node modules. After browserify the `EventBus(...)` call produces and error saying that EventBus is not a function.

I do get the following error even though the url connection is tried:

`Error: (SystemJS) Cannot set property 'onopen' of undefined↵	TypeError: Cannot set property 'onopen' of undefined↵	    at Module.EventBus (http://127.0.0.1:8080/node_modules/vertx3-eventbus-client/vertx-eventbus.js:98:28)`

Being a JS/TS newbee I cannot tell if this is due to being called from TS or if it is just a side effect of target URL not being available, or something else.

**Comment by neal-eiger** [comment]
I also am trying to use this, with an angular 4 app.  There is no issue at compile time but at run time I have the above issue:

`import EventBus from 'vertx3-eventbus-client';
let eventBus = new EventBus("http://locahost/eventbus");  // error: d.default is not a constructor
let eventBus = EventBus("http://locahost/eventbus");  // error: d.default is not a function`

Im using webpack atm, and the transpiled code shows that d is in fact a variable (haven't researched it further).  I don't have any other issues like this and its a bummer not to be able to use vertx in a modern, modular way.

While its true there are not type definitions I dont think that's the issue.  The version of sockjs-client it seems to be using from the node_module under vertx3-eventbus-client looks strange but I assume it works when included in the browser as did version 2 of vertx client.  

It would be nice if someone in the know has a suggestion, as vertx is the only part of our client app not working with webpack, and debugging this it taking a good bit of time.

**Comment by pmlopes** [comment]
@neal-eiger can you provide a reproducer?

**Comment by neal-eiger** [comment]
Hi @pmlopes.  Thanks for getting back.  Im working on an internal project, but maybe tomorrow if I still can't get it I'll make a small mock project to show the failure.  On the other hand do you know of a seed project using webpack, vertx-eventbus-client, and angular 2 or 4 (ie. with Typescript)?  

So far I created a typescript version of vertx-eventbus.js, but then SockJS threw the same error, saying that SockJS is not a constructor.  So then I installed @types/sockjs-client, but then the browser throws the error on load that 'fs' not defined (as in the node variable).  I defined target:node, but then exports is not defined....  Haha.

Im new to webpack and use Java on the server side, as well as currently porting from systemjs, so just going through the motions trying to eliminate possible errors, will start porting to webpack from scratch tomorrow again in hopes of taking a better path.

However, if you have any ideas on importing/using vertx-eventbus.js with Typescript on a webpack project I'd be happy to hear.

**Comment by neal-eiger** [comment]
Just to update, I just read this which echoes what's been said in this thread: if you include vertx-eventbus.js script directly on the page it works (as well as declaring the type for typescript), but it doesnt work if you try and import it into the bundle and that's a shame.  Will follow up later.

**Comment by neal-eiger** [comment]
I forked a little repo and added vertx3-eventbus-client and you can can see the error.  Please clone or fork https://github.com/neal-eiger/angular-webpack, npm i && npm start.  Go to localhost:8080 and look at the console.  You will find this error:

Unhandled Promise rejection: vertx3_eventbus_client_1.EventBus is not a constructor ; Zone: <root> ; Task: Promise.then ; Value: TypeError: vertx3_eventbus_client_1.EventBus is not a constructor

Would be great if you could suggest the fix.  You can also comment out the 2 vertx related lines I added into src/app/app.component.ts and you will see the app runs fine again.

**Comment by pmlopes** [comment]
@neal-eiger @tombensve you're importing the module not correctly.

The original module exports a single function, not a object so in order to import it correctly you should do:

```js
import * as EventBus from 'vertx3-eventbus-client';
```

**Comment by neal-eiger** [comment]
Thought I tried that as I use that import syntax with momentjs, but I guess not, thanks!  It may be worth putting that in your readme though as a number of others seem to have had the same issue.  Have a good weekend and thanks again.

**Comment by tombensve** [comment]
Interesting! I've been away from my "hobby project" for a while. I'll give this a try. Thanks.

**Comment by mikeagarza** [comment]
I ran across this TypeScript version of the EventBus the other day:  https://gist.github.com/benorama/93373c3c1c3574732d6cc1b4754aab9f

**Comment by oddeirik** [comment]
I added the definitions as a PR to the DefinitelyTyped project, and it has now been merged. So anyone using the EventBus bridge in a Typescript project should now be able to just add @types/vertx3-eventbus-client as a dependency:

`npm install --save @types/vertx3-eventbus-client`
(https://www.npmjs.com/package/@types/vertx3-eventbus-client)

Ideally, I'd like to see "official" typings (or even better, a Typescript version, similar to what's done in the gist above) from the Vertx team, but this works well enough for me at the moment, so I'd rather they focus their efforts on the JVM side of things 😄

**Comment by pmlopes** [comment]
I'm not sure if a port to TypeScript would make it better but i believe that we could work on getting the JS code to play better with both typescript type definitions or other typing systems out there such as flow.

This way we could have the same base for browser, server, typescript and ES6+

**Comment by oddeirik** [comment]
Absolutely, that would be good! I wasn't implying that a TS version would be better, just that this would give us typings for "free".

**Comment by joshi-gaurav** [comment]
Can [ES6 Version of EventBus](http://www.kalpsnuti.com/eventbus-es6-version/) be of an use?

**Comment by tombensve** [comment]
I tried the "https://gist.github.com/benorama/93373c3c1c3574732d6cc1b4754aab9f" posted by mikeagarza. This one works perfectly from Typescript, probably due to it being written in Typescript :-)

**Comment by SanthoshKumarKatta** [comment]
Hi,

eb.send always getting null. The connection was established and Service returned one JSON object.

var eb = new EventBus('http://localhost:40400/test');
eb.onopen = function () {
console.log('eb.onopen start.');
eb.send('MY_SERVICE',OBJ, function (reply) {
console.log("receive message: " + JSON.stringify(reply));  // This is getting null always//
});

I'm using - Angular (vertx3-eventbus-client) and Java Vertx. Please help me in fixing this.

Thanks,
Santhosh Katta

**Comment by pmlopes** [comment]
@SanthoshKumarKatta your callback should follow the node style:

```js
function (error, reply) {
  ...
}
```

**Comment by Mediaus** [comment]
Can anyone suggest on writing Observables in Angular? Tried many ways to do this and failing. I'm having a very hard time to do this.

Thanks in advance! 

Here is my Service. 

export class Login {

    res: any = {};
    login(user: any): Observable<any>{
        var eb = new EventBus('http://localhost:40400/test');
        eb.enableReconnect(true);
        eb.onopen = function () {
         };
        eb.enableReconnect(true);
          return eb.send(s.test, user, (error, reply) => {
                console.log("reply:"+ JSON.stringify(reply));
                this.res = reply;
            //    observer.next(this.res);
                }).map((res: Response) => res.json());
            // return Observable.create(observer => {
            //     console.log("this.res:" + JSON.stringify(this.res));
            //     observer.next(this.res);
            //    })
    }
}

**Comment by SanthoshKumarKatta** [comment]
Can anyone suggest on writing Observables using EventBus in Angular? Tried many ways to do this and failing. I'm having a very hard time to do this.

Thanks in advance!

Here is my Service.

export class Login {

res: any = {};
login(user: any): Observable<any>{
    var eb = new EventBus('http://localhost:40400/test');
    eb.enableReconnect(true);
    eb.onopen = function () {
     };
    eb.enableReconnect(true);
      return eb.send(s.test, user, (error, reply) => {
            console.log("reply:"+ JSON.stringify(reply));
            this.res = reply;
        //    observer.next(this.res);
            }).map((res: Response) => res.json());
        // return Observable.create(observer => {
        //     console.log("this.res:" + JSON.stringify(this.res));
        //     observer.next(this.res);
        //    })
}
}

**Comment by pmlopes** [comment]
type definitions are available on `npm install --save @types/vertx3-eventbus-client`
