### ISSUE TITLE
How to set the timeout for vertx3-eventbus-client

### ISSUE THREAD

**Issue by Lakshmihm** [vert-x3/vertx-stack#76]
Hi,

Just wanted to check if there is a way to set the timeout from sender end when we do eventBus.send(..) in node js?
Tried setting "timeout" header, but that didn't help. 
There is DeliveryOptions in Java but how to set the timeout in javascript? Any response is appreciated. Thanks

**Comment by tsegismont** [comment]
I don't believe this is possible currently. Would you mind to open a feature request on the [vertx-web](https://github.com/vert-x3/vertx-web/issues/new) project?

Closing this issue as this is not the right project.
