### ISSUE TITLE
Inconsistence Docs for Logging: Docker and Rest of Docs

### ISSUE THREAD

**Issue by StephenOTT** [vert-x3/vertx-stack#79]
been going through the logging docs and there seems to be confusing inconsistencies between directions around logging for Docker deployments and the rest of the Vertx docs.

As a primary example:
What is the reason for the docker docs to use `logging.properties` as the file: http://vertx.io/docs/vertx-docker/#_logging along with ENV vars, but the rest of the docs all use `vertx-default-jul-logging.properties` as their examples:

Hazelcast: http://vertx.io/docs/vertx-hazelcast/java/#_enabling_logging
Core: http://vertx.io/docs/vertx-core/js/#_logging
From core:
>A JUL logging configuration file can be specified in the normal JUL way by providing a system property called: java.util.logging.config.file with the value being your configuration file. For more information on this and the structure of a JUL config file please consult the JUL logging documentation.

>Vert.x also provides a slightly more convenient way to specify a configuration file without having to set a system property. Just provide a JUL config file with the name vertx-default-jul-logging.properties on your classpath (e.g. inside your fatjar) and Vert.x will use that to configure JUL.

Happy to do a PR to update docs.  Just want to get direction around the usage and history.

**Comment by tsegismont** [comment]
@StephenOTT the `vertx-default-jul-logging.properties` file is just a convenient way to configure JUL when you're able to add something to the classpath. You could have a `logging.properties` file anywhere on the FS and use it together with the `java.util.logging.config.file` sysprop.

In the `vertx-docker` example however, we're talking about applications started with the Vert.x CLI. In this case, the user may either configure the `conf/logging.properties` CLI file or set the `VERTX_JUL_CONFIG` env var.

**Comment by StephenOTT** [comment]
> the user may either configure the conf/logging.properties

Is there a folder structure documentation of vertx projects?  I dont come from a java dev background.  So looking for where the defaulted folders and use cases are.  I have seen `/conf/` used in a few examples, but no documentation about when it is being used.

**Comment by tsegismont** [comment]
@StephenOTT `/conf` here is not a project directory but a directory in the CLI installatio

@cescoffier do we have documentation for CLI layout and stack update? I couldn't find it in vertx-core doc

**Comment by cescoffier** [comment]
@tsegismont I don't think we have this documented. We more or less inherited this from Vert.x 2.

**Comment by tsegismont** [comment]
@cescoffier so a PR to core doc would be best, correct?

**Comment by cescoffier** [comment]
@tsegismont yes.

**Comment by cescoffier** [comment]
@tsegismont actually, it may be better to document it in the stack manager manual (https://github.com/vert-x3/vertx-stack/blob/master/stack-manager/src/main/java/io/vertx/stack/command/package-info.java). The manual does not provide any details about the structure, I believe it should live there. But at the same time the vert.x core doc contains the doc for the `vertx` cli.

**Comment by StephenOTT** [comment]
@tsegismont @cescoffier so what can go into `/conf`?

`/conf` if a pattern used in other java projects, correct?

**Comment by tsegismont** [comment]
Closing, Docker images are no longer provided anyway
