### ISSUE TITLE
Documentation update for VERTX_HOME env variable in Docker Containers

### ISSUE THREAD

**Issue by StephenOTT** [vert-x3/vertx-stack#80]
Docs use `COPY vertx-stack.json ${VERTX_HOME}/vertx-stack.json`, but there does not appear to be explanation of where VERTX_HOME comes from, its location, and the usage.

This is a important aspect for the Stack manager: http://vertx.io/docs/vertx-stack-manager/stack-manager/

as the docs for stack manager, under the http://vertx.io/docs/vertx-stack-manager/stack-manager/#_launching_the_resolution section read: 

>If you have set VERTX_HOME as environment variable (or system variable), it uses: $VERTX_HOME/lib and $VERTX_HOME/vertx-stack.json.

Without context it could easily be confused as something variation of the ENV var: `VERTICLE_HOME`

Happy to do a PR, just looking for context and explanation of the usage.

**Comment by tsegismont** [comment]
It's just used in the [Customizing the stack](http://vertx.io/docs/vertx-docker/#_customizing_the_stack).

But yes, the second callout could be updated with a note explaining where the VERTX_HOME env comes from.

**Comment by tsegismont** [comment]
> what files go into VERTX_HOME (cluster.xml)

No `cluster.xml` is a per-instance configuration file. Shouldn't go to the CLI installation directory.

`VERTX_HOME` is the CLI installation dir so the only file you should update there is the stack configuration.

**Comment by StephenOTT** [comment]
Yes. Sorry typo on my side.

**Comment by StephenOTT** [comment]
@tsegismont what are your thoughts on the ruby gems.  Example: in the gemfile import scenario I raised in the other issues. Do you see that ruby vendor/bundle folder should go in vertx_home or verticle home?

**Comment by tsegismont** [comment]
@StephenOTT I'm not knowledgeable in this area. Perhaps you could ask on the user forum how Ruby users in the community deal with gem loading.
