### ISSUE TITLE
Docker clustering configuration docs: -cp implementation inconsistency

### ISSUE THREAD

**Issue by StephenOTT** [vert-x3/vertx-stack#82]
Hey

looking at: http://vertx.io/docs/vertx-docker/#_clustering

Trying to understand the reason for generating a dynamic class path in the docs example: 

>To build a dynamic classpath from all the file contained in $VERTICLE_HOME you can use:....

In each of the dockerfile examples in the docs you use:

`CMD ["exec vertx run $VERTICLE_NAME -cp $VERTICLE_HOME/*"]`  where the `-cp` is using `$VERTICLE_HOME/*`. assuming that `*` provides "everything" in $VERTICLE_HOME logic.

Looking at http://vertx.io/docs/vertx-core/js/#_the_vertx_command_line, there does not appear to provide usage of `*`, so is this just out of date docs on docker + vertx command line usage?

happy to provide PRs as always for doc updates.  Just trying to understand the various usages based on the docs.

Thanks!

**Comment by tsegismont** [comment]
I don't believe wildcards in classpath definition works. That said, the solution proposed seems complex to me. A simple `vertx.hazelcast.config` sysprop pointing to the cluster.xml file would do.

**Comment by tsegismont** [comment]
@StephenOTT mm indeed, I wasn't aware of that. Can you confirm @cescoffier ? Why this complex dynamic classpath thing then?

**Comment by cescoffier** [comment]
I used "*" without trouble. Can you provide an example? It may depend on the `CMD` command

**Comment by StephenOTT** [comment]
@cescoffier, see the the first post: https://github.com/vert-x3/vertx-stack/issues/82#issue-298122631

The question is related all of the docker examples in vertx/examples having the `/*` in them.  also the docs have the same examples.

**Comment by tsegismont** [comment]
Closing, Docker images are no longer provided anyway
