### ISSUE TITLE
Add micrometer metrics in the stack

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-stack#85]
- various langs + rx
- vertx-stack

**Comment by vietj** [comment]
cc @jotak

**Comment by jotak** [comment]
There's PR #77

**Comment by vietj** [comment]
can you check the PR still work ? in the meantime the documentation part has been changed due to the stack rework

**Comment by jotak** [comment]
@vietj I cannot verify the build due to many missing dependencies at the moment on 3.6.0-SNAPSHOT : not only micrometer but others like consul, camel-bridge, zookeeper and probably many other.
Is there a staging repo that I should configure?

**Comment by jotak** [comment]
even with that some are missing (consul , camel-bridge ...)

**Comment by vietj** [comment]
that's weird

**Comment by vietj** [comment]
@jotak I think we are actually done with this task :-)
