### ISSUE TITLE
Possible to build a raspberry pi version?

### ISSUE THREAD

**Issue by cranphin** [vert-x3/vertx-stack#96]
Hi!

It would be great if there was an image for the Raspberry Pi architecture on docker hub too, is it possible to do that?

I'm not sure what would be involved in that, I think the openjdk base image is already available for ARM.

Thanks for your attention! :)

**Comment by pmlopes** [comment]
If you already a base image with java you can just copy your fat-jars into a new layer and it should run. I can confirm that without docker, just a RPi2 and RPi3 using the available jdk package I can run vert.x applications.

**Comment by cranphin** [comment]
Hi!

The downside of a fatjar is that it's a lot more data to deploy each time on a resource contrained device :)

But I looked at your dockerfiles and can build my own locally now: https://github.com/cranphin/vertx3-alpine-docker (on the rpi), which is easy enough and solves my issue :)

Soon it should be 'easy' to build multipe arch images from any platform too: https://engineering.docker.com/2019/04/multi-arch-images/ but it's a very relative easy.. :)

**Comment by cranphin** [comment]
Actually, since this is Java, a trick like this would also work: https://stackoverflow.com/questions/54051697/how-to-build-docker-container-image-for-arm32-architecture-from-windows-10-os :)
